### PR TITLE
cln: bitcoin-rpcport is now an int in CLN 23.08

### LINKED ISSUE #225: PeerSwap doesn't start if using CLN 23.08 and if bitcoin-rpcport is set in CLN config
When running CLN 23.08, if `bitcoin-rpcport` is set in the CLN config, PeerSwap fails to start: 

```
2023-08-24T14:49:01.937Z INFO    plugin-peerswap: PeerSwap starting up with commit 19eeea491fe39cad78302096b6b2bd922af61be8
2023-08-24T14:49:01.937Z INFO    plugin-peerswap: DB version: v0.2, Protocol version: 3
2023-08-24T14:49:01.937Z INFO    plugin-peerswap: Using data dir: /home/user/.lightning/signet
2023-08-24T14:49:01.941Z INFO    plugin-peerswap: Killing plugin: exited during normal operation
```

Commenting `bitcoin-rpcport` out fixes it and PeerSwap is able to start. 

CLN 23.08 introduced a change to `listconfigs`. Could this be the root cause?

### PR DESCRIPTION
**Pull request by grubles**
`bitcoin-rpcport` is now an integer in CLN 23.08. Go unmarshals JSON numbers into a `float64` by default, so we need to convert that to a `uint` to make PeerSwap happy. 

Should fix #225.

### CODE REVIEW

File: clightning/config.go [hunk 1]
```diff
@@ -271,11 +271,16 @@ func BitcoinFallbackFromClnConfig(client *ClightningClient) Processor {
...
-								return nil, err
+							// detect if type is string (CLN < v23.08)
+							if reflect.TypeOf(v).String() == "string" {
+								port, err := strconv.Atoi(v.(string))
+								if err != nil {
+									return nil, err
+								c.Bitcoin.RpcPort = uint(port)
+								}
+							} else {
+								c.Bitcoin.RpcPort = uint(v.(float64))
```
Comment (nepet) [inline clightning/config.go:282]: Nice that you also thought about backwards compatibility!
Instead of reflection (which is more powerful but also requires more memory and is slower) we could take the direct and idiomatic way, using type assertions. This way we could use a "type switch" that could also tell us about cases we missed or that we have not covered on future changes of external apis.
```suggestion
							// detect if type is string (CLN < v23.08)
							switch p := v.(type) {
							case string:
							        port, err := strconv.Atoi(p)
								if err != nil {
									return nil, err
							        }
							        c.Bitcoin.RpcPort = uint(port)
							case float64:
							        c.Bitcoin.RpcPort = uint(p)
							default:
							        return nil, fmt.Errorf("Bitcoind rpcport type %T not handled", v)
							}
```

**Review by nepet — CHANGES_REQUESTED** [review]

**Comment by nepet** [comment]
If I got it right, this should not only fix #225 but also #224?

**Comment by grubles** [comment]
Let's go with your suggestion. Yes 224 should be fixed as well!

**Review by nepet — APPROVED** [review]
:+1:
